default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kerosene_development
  port: 5432
  username: postgres
  #password: kerosene
  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  #port: 5432

  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  #min_messages: notice

test:
  <<: *default
  host: localhost
  username: postgres
  port: 5432
  #password: kerosene
  database: kerosene_test

production:
  primary: &primary_production
    <<: *default
    host: db
    username: postgres
    database: kerosene_production
    port: 5432
    password: <%= Rails.application.credentials.dig(:database, :primary_password) %>
  cache:
    <<: *primary_production
    host: db
    username: postgres
    port: 5432
    #password: <%= Rails.application.credentials.dig(:database, :secondary_password) %>
    database: kerosene_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    host: db
    username: postgres
    port: 5432
    #password: <%= Rails.application.credentials.dig(:database, :secondary_password) %>
    database: kerosene_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    host: db
    username: postgres
    port: 5432
    #password: <%= Rails.application.credentials.dig(:database, :secondary_password) %>
    database: kerosene_production_cable
    migrations_paths: db/cable_migrate
