name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t kerosene .

      - name: Push the Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/sbeltranc/kerosene:latest
            ghcr.io/sbeltranc/kerosene:${{ github.sha }}
